-- MySQL Script generated by MySQL Workbench
-- Fri Mar 16 20:10:25 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema artdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema artdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `artdb` DEFAULT CHARACTER SET utf8 ;
USE `artdb` ;

-- -----------------------------------------------------
-- Table `artdb`.`Exposicion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `artdb`.`Exposicion` (
  `CodExpo` INT NOT NULL,
  `NomExpo` VARCHAR(150) NOT NULL,
  `MoviExpo` VARCHAR(45) NOT NULL,
  `TipoObra` VARCHAR(45) NULL,
  PRIMARY KEY (`CodExpo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `artdb`.`Entidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `artdb`.`Entidad` (
  `CodEnti` INT NOT NULL auto_increment,
  `NomEnti` VARCHAR(45) NOT NULL,
  `TipoEnti` VARCHAR(45) NULL,
  PRIMARY KEY (`CodEnti`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `artdb`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `artdb`.`Persona` (
  `CodPer` INT NOT NULL auto_increment,
  `NomPer` VARCHAR(45) NOT NULL,
  `ApePer` VARCHAR(45) NULL,
  `Sexo` VARCHAR(45) NULL,
  `Titulacion` VARCHAR(45) NULL,
  `TipoPer` VARCHAR(45) NULL,
  PRIMARY KEY (`CodPer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `artdb`.`ExpoEnti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `artdb`.`ExpoEnti` (
  `CodExpoEnti` INT NOT NULL auto_increment,
  `CodExpo` INT NOT NULL,
  `CodEnti` INT NOT NULL,
  `FechaIni` DATE NULL,
  `FechaFin` DATE NULL,
  PRIMARY KEY (`CodExpoEnti`),
  INDEX `fk_ExpoEnti_Exposicion_idx` (`CodExpo` ASC),
  INDEX `fk_ExpoEnti_Entidad1_idx` (`CodEnti` ASC),
  CONSTRAINT `fk_ExpoEnti_Exposicion`
    FOREIGN KEY (`CodExpo`)
    REFERENCES `artdb`.`Exposicion` (`CodExpo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ExpoEnti_Entidad1`
    FOREIGN KEY (`CodEnti`)
    REFERENCES `artdb`.`Entidad` (`CodEnti`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `artdb`.`ExpoPer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `artdb`.`ExpoPer` (
  `CodExpoPer` INT NOT NULL auto_increment,
  `CodExpo` INT NOT NULL,
  `CodPer` INT NOT NULL,
  PRIMARY KEY (`CodExpoPer`),
  INDEX `fk_ExpoPer_Exposicion1_idx` (`CodExpo` ASC),
  INDEX `fk_ExpoPer_Persona1_idx` (`CodPer` ASC),
  CONSTRAINT `fk_ExpoPer_Exposicion1`
    FOREIGN KEY (`CodExpo`)
    REFERENCES `artdb`.`Exposicion` (`CodExpo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ExpoPer_Persona1`
    FOREIGN KEY (`CodPer`)
    REFERENCES `artdb`.`Persona` (`CodPer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;